Remove weird GCC optimization hacks from fmt
This somehow breaks the build with gcc 10.2.1 on Debian 11:

Patchage.cpp:907:1: error: macro "__OPTIMIZE__" is not used [-Werror=unused-macros]

Header libraries messing with optimization flags is wildly inappropriate
anyway.